[package]
name = "reforum"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "reforum"


[dependencies]
eyre = "0.6"
color-eyre = "0.6"
thiserror = "1"

# entity = { path = "entity" }
# migration = { path = "migration" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

config = "0.13"

axum = "0.5"
axum-extra = { version = "0.3.6", features = [ "cookie-signed" ] }
maud = { version = "0.23", features = [ "axum" ] }

hyper = "0.14"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4" }
tower-http = { version = "0.3", features = ["full"]}
cookie = { version = "0.16", features = [ "secure" ] }
async-trait = "0.1"
futures = { version = "0.3", features = ["executor"] }

deadpool-sqlite = { version = "0.5", features = [ "rt_tokio_1",  "serde" ] }
rusqlite_migration = "1"

nanoid = "0.4"
base64 = "0.13"
sha2 = "0.10"
hmac = { version = "0.12", features = ["std"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

secrecy = { version = "0.8", features = ["serde"] }
validator = "0.15"
argon2 = { version = "0.4", features = ["std"] }

itertools = "0.10"
time = "0.3"

[dependencies.rusqlite]
version = "0.28"
features = [
    "array",
    "bundled",
    "backup",
    "blob",
    "modern_sqlite",
    "collation",
    "column_decltype",
    "csvtab",
    "extra_check",
    "functions",
    "hooks",
    "i128_blob",
    "limits",
    "load_extension",
    "serde_json",
    "series",
    "time",
    "trace",
    "unlock_notify",
    "url",
    "uuid",
    "vtab",
    "window",
]

# [dependencies.sqlx]
# version = "0.6"
# features = [
#     "runtime-tokio-rustls",
#     "macros",
#     "sqlite",
#     "uuid",
#     "time",
#     "migrate",
#     "offline",
# ]